server:
  port: 9008

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cloud.yxb.cool:9306/tiny_im?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    url: jdbc:mysql://localhost:3306/tiny_love?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: tiny_im_user
    password: Tiny_im_0108
#    username: root
#    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

logging:
  level:
    com.yxb: debug
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.yxb.*.domain
  global-config:
    db-config:
      id-type: uuid
  configuration:
    cache-enabled: false
websocket:
  port: 9009